spring:
   application:
      name: blogging-app
   datasource:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:file:./test;
      
   jpa:
      hibernate:
         ddl-auto: create #in prod, use update, NOT create

server:
   port: 8800
      
springdoc:
   swagger-ui:
      path: /index.html